---
language: node_js
node_js:
  - "4.2.1"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

addons:
    code_climate:
        repo_token: 539c888c9f66f042bfa7ee0cf48b78d19e640b73a9fe2b1c8cf4230d4de3bd3c

after_script:
  - codeclimate-test-reporter < lcov.info

after_success:
  - npm install -g firebase-tools
  - ember build
  - firebase deploy --token ${FIREBASE_TOKEN}
